#!/bin/bash
# Build the ISS (QEMU) with the current configuration.

set -e

iss_build_path="$ISS_DIR/build"

# Get QEMU target name from environment of default to "vadl-softmmu"
target=${QEMU_TARGET:-"vadl-softmmu"}
# If file $ISS_DIR/build does not exist, we have to configure QEMU first
if [ ! -f "$iss_build_path" ]; then
    mkdir -p $iss_build_path
    cd $iss_build_path
    ../configure --cc='ccache gcc' --target-list=$target
fi

cd $iss_build_path

make -j$(nproc)
