#!/bin/bash

set -e

test_scripts_path="$OPEN_VADL_DIR/vadl-test/main/resources/scripts/iss_qemu"

test_runner="$test_scripts_path/bare_metal_runner.py"

cd "$TESTSUITE_DIR"

python3 "$test_runner" "$ISS_DIR/build/qemu-system-vadl"
