#!/bin/bash
# Executes the vadl binary to generate the ISS for the RV64I ISA.

set -e

echo "Generating ISS for RV64I specification..."

cd "$GEN_DIR"

rv64i_spec="$OPEN_VADL_DIR/vadl-test/main/resources/testSource/sys/risc-v/rv64i.vadl"

time vadl --viam-iss $rv64i_spec

echo "Done."