#!/bin/bash
# Executes the vadl binary to generate the ISS for the RV64I ISA.

set -e


cd "$GEN_DIR"
spec_path="$OPEN_VADL_DIR/sys/$1"

echo "Generating ISS from $spec_path specification..."

time openvadl iss -o /$GEN_DIR $spec_path ${@:2}

echo "Done."